-- Step 1: Create the database
CREATE DATABASE IF NOT EXISTS libManagement;
USE libManagement;

-- Step 2: Create the Users table
CREATE TABLE IF NOT EXISTS Users (
    username VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    role VARCHAR(50) DEFAULT 'user'
);

-- Step 3: Create the Books table
CREATE TABLE IF NOT EXISTS Books (
    isbn VARCHAR(20) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL
);

INSERT INTO Users (username, password, email, role)
VALUES ('administrator', 'your_hashed_password', 'admin@domain.com', 'admin'); -- password is 'admin' hashed

-- Insert 100 dummy books into the Books table
INSERT INTO Books (isbn, title, author) VALUES
('ISBN001', 'The Midnight Garden', 'Elizabeth Hartley'),
('ISBN002', 'Echoes of Silence', 'Marcus Rodriguez'),
('ISBN003', 'Quantum Horizon', 'Dr. Sarah Chen'),
('ISBN004', 'Whispers in the Wind', 'Robert J. Thompson'),
('ISBN005', 'The Last Manuscript', 'Anna Kowalski'),
('ISBN006', 'Crimson Skies', 'Jack Harrison'),
('ISBN007', 'Beneath the Starlight', 'Maria Elena Rodriguez'),
('ISBN008', 'The Forgotten Path', 'David Nguyen'),
('ISBN009', 'Shadows of Berlin', 'Klaus Mueller'),
('ISBN010', 'The Ocean''s Secret', 'Olivia Sinclair'),
('ISBN011', 'Coding Revolution', 'Alex Peterson'),
('ISBN012', 'Silent Echoes', 'Emma Watkins'),
('ISBN013', 'The Philosopher''s Stone', 'Dr. William Richards'),
('ISBN014', 'Lunar Descent', 'Katherine Armstrong'),
('ISBN015', 'The Ancient Cipher', 'Thomas Blackwood'),
('ISBN016', 'Rogue Algorithm', 'Jennifer Liu'),
('ISBN017', 'Winds of Change', 'Carlos Ramirez'),
('ISBN018', 'The Hidden City', 'Sophia Martinez'),
('ISBN019', 'Quantum Entanglement', 'Dr. Michael Green'),
('ISBN020', 'Twilight''s Edge', 'Rachel Bennett'),
('ISBN021', 'The Genetic Key', 'Dr. James Wong'),
('ISBN022', 'Midnight Protocol', 'Elena Petrova'),
('ISBN023', 'The Lost Symphony', 'Christopher Davis'),
('ISBN024', 'Cybernetic Dreams', 'Janice Lee'),
('ISBN025', 'Eternal Horizon', 'Samuel Kimura'),
('ISBN026', 'The Silk Road', 'Ahmed Hassan'),
('ISBN027', 'Quantum Paradox', 'Dr. Emily Chang'),
('ISBN028', 'Whispers of War', 'Michael O''Brien'),
('ISBN029', 'The Forgotten Realm', 'Isabella Torres'),
('ISBN030', 'Celestial Mechanics', 'Dr. Robert Kim'),
('ISBN031', 'The Crimson Manuscript', 'Victoria Anderson'),
('ISBN032', 'Echoes of Eternity', 'Daniel Park'),
('ISBN033', 'The Neural Network', 'Jessica Wong'),
('ISBN034', 'Shadows of Perception', 'Alexander Volkov'),
('ISBN035', 'The Quantum Leap', 'Dr. Sophia Nakamura'),
('ISBN036', 'Midnight Inheritance', 'Rebecca Collins'),
('ISBN037', 'The Cosmic Code', 'Gregory Thompson'),
('ISBN038', 'Silent Waves', 'Maya Patel'),
('ISBN039', 'The Genetic Frontier', 'Dr. Jonathan Lee'),
('ISBN040', 'Whispers of Time', 'Amanda Richards'),
('ISBN041', 'The Digital Divide', 'Ryan Martinez'),
('ISBN042', 'Quantum Resonance', 'Dr. Elizabeth Kim'),
('ISBN043', 'The Hidden Algorithm', 'Nicolas Lambert'),
('ISBN044', 'Echoes of Rebellion', 'Sarah O''Connor'),
('ISBN045', 'The Starlight Equation', 'Dr. David Chen'),
('ISBN046', 'Midnight Horizon', 'Laura Gonzalez'),
('ISBN047', 'The Cipher''s Secret', 'Andrew Nakamura'),
('ISBN048', 'Quantum Shadows', 'Dr. Rachel Zhang'),
('ISBN049', 'The Lost Code', 'Mark Sullivan'),
('ISBN050', 'Echoes of Silence', 'Elena Rodriguez'),
('ISBN051', 'The Quantum Archive', 'Dr. Peter Wang'),
('ISBN052', 'Midnight Convergence', 'Sophie Martin'),
('ISBN053', 'The Neural Frontier', 'Jason Liu'),
('ISBN054', 'Shadows of Destiny', 'Michelle Tanaka'),
('ISBN055', 'The Cosmic Cipher', 'Dr. Daniel Kim'),
('ISBN056', 'Whispers of the Future', 'Emma Thompson'),
('ISBN057', 'The Genetic Horizon', 'Dr. Lisa Chen'),
('ISBN058', 'Midnight Protocol', 'Kevin Rodriguez'),
('ISBN059', 'The Digital Enigma', 'Natalie Park'),
('ISBN060', 'Quantum Entanglement', 'Dr. Alexander Wong'),
('ISBN061', 'The Hidden Network', 'Brian Collins'),
('ISBN062', 'Echoes of Infinity', 'Samantha Lee'),
('ISBN063', 'The Starlight Code', 'Dr. Michael Zhang'),
('ISBN064', 'Midnight Equation', 'Julia Martinez'),
('ISBN065', 'The Neural Cipher', 'Christopher Kim'),
('ISBN066', 'Shadows of Innovation', 'Dr. Rachel Chen'),
('ISBN067', 'The Quantum Manuscript', 'Eric Thompson'),
('ISBN068', 'Whispers of Encryption', 'Olivia Nakamura'),
('ISBN069', 'The Cosmic Algorithm', 'Dr. David Park'),
('ISBN070', 'Midnight Horizon', 'Maria Rodriguez'),
('ISBN071', 'The Digital Symphony', 'Dr. Jonathan Wong'),
('ISBN072', 'Echoes of Singularity', 'Nathan Lee'),
('ISBN073', 'The Genetic Code', 'Dr. Sarah Kim'),
('ISBN074', 'Quantum Shadows', 'Rebecca Martinez'),
('ISBN075', 'The Hidden Horizon', 'Dr. Michael Chen'),
('ISBN076', 'Midnight Resonance', 'Jacob Rodriguez'),
('ISBN077', 'The Neural Network', 'Dr. Emily Zhang'),
('ISBN078', 'Shadows of Discovery', 'Lucas Thompson'),
('ISBN079', 'The Quantum Inheritance', 'Dr. Daniel Park'),
('ISBN080', 'Whispers of Innovation', 'Sophia Liu'),
('ISBN081', 'The Cosmic Cipher', 'Dr. Robert Wong'),
('ISBN082', 'Midnight Protocol', 'Isabella Chen'),
('ISBN083', 'The Digital Frontier', 'Dr. James Kim'),
('ISBN084', 'Echoes of Transformation', 'Alexander Rodriguez'),
('ISBN085', 'The Starlight Equation', 'Dr. Katherine Zhang'),
('ISBN086', 'Midnight Horizon', 'Emma Martinez'),
('ISBN087', 'The Neural Manuscript', 'Dr. William Park'),
('ISBN088', 'Shadows of Possibility', 'Victoria Lee'),
('ISBN089', 'The Quantum Archive', 'Dr. Thomas Chen'),
('ISBN090', 'Whispers of Progress', 'Nicholas Wong'),
('ISBN091', 'The Genetic Frontier', 'Dr. Elizabeth Kim'),
('ISBN092', 'Midnight Convergence', 'Daniel Rodriguez'),
('ISBN093', 'The Digital Enigma', 'Dr. Sarah Zhang'),
('ISBN094', 'Echoes of Innovation', 'Michael Thompson'),
('ISBN095', 'The Cosmic Network', 'Dr. Jennifer Park'),
('ISBN096', 'Quantum Shadows', 'Rachel Chen'),
('ISBN097', 'The Hidden Code', 'Dr. David Wong'),
('ISBN098', 'Midnight Equation', 'Sophia Rodriguez'),
('ISBN099', 'The Neural Cipher', 'Dr. Christopher Kim'),
('ISBN100', 'Echoes of Discovery', 'Dr. Elena Martinez');